// examples/mv3-react-ts-vite/src/entries/sandbox/App.tsx
import { useEffect } from "react"

function App() {
  useEffect(() => {
    setTimeout(() => {
      eval(`
      alert("我是 sandbox eval alert")
      `)
    }, 1000)
  }, [])
  return (
    <div>
      <h1>sandbox</h1>
      <ul>{Object.keys(chrome).map(item => <li key={item}>{item}</li>)}</ul>
    </div>
  )
}

export default App

// examples/mv3-vue-ts-vite/src/entries/sandbox/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'

onMounted(() => {
  setTimeout(() => {
    eval(`
      alert("我是 sandbox eval alert")
      `)
  }, 1000)
})
const chromeKeys = Object.keys(chrome)
</script>

<template>
  <div>
    <h1>sandbox</h1>
    <ul>
      <li v-for="item in chromeKeys" v-bind:key="item">
        {{ item }}
      </li>
    </ul>
  </div>
</template>

<style scoped></style>
