// examples/mv3-react-ts-vite/src/entries/newtab/App.tsx
import { useCallback } from 'react'

function App() {
  const testSandbox = useCallback(async () => {
    const url = chrome.runtime.getURL('main.html')
    await chrome.tabs.create({ url })
  }, [])

  return (
    <div>
      <h1>newtab</h1>
      <ul>
        {Object.keys(chrome).map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
      <button onClick={testSandbox}>打开 main.html 测试 sandbox.html</button>
    </div>
  )
}

export default App

// examples/mv3-vue-ts-vite/src/entries/main/App.vue
<script setup lang="ts">
const chromeKeys = Object.keys(chrome)
const sandboxUrl = chrome.runtime.getURL('sandbox.html')
</script>

<template>
  <div>
    <h1>main</h1>
    <ul>
      <li v-for="item in chromeKeys" v-bind:key="item">
        {{ item }}
      </li>
    </ul>
    <iframe :src="sandboxUrl" width="400" height="400"></iframe>
  </div>
</template>

<style scoped></style>
